### ISSUE TITLE
Conjunctions are missing

### ISSUE THREAD

**Issue by mastizada** [mozillaz/spellchecker#6]
@seferov @fardinshikhiyev we need list of conjunctions.

**Comment by mastizada** [comment]
və, və ya, həm və s.

**Comment by fardinshikhiyev** [comment]
**Tabesizlik bağlayıcıları:**

1. Birləşdirmə bağlayıcıları: və, ilə (-la<sup>2</sup>)
2. İnkarlıq bağlayıcıları: nə, nə də, nə də ki.
3. Qarşılaşdırma bağlayıcıları:  amma, ancaq, lakin, fəgət, halbuki, yoxsa, isə.
4. Bölüşdürmə bağlayıcıları: ya, ya da, ya da ki, və ya, gah, gah da, gah da ki, istər, istərsə, istərsə də, yaxud.
5. İştirak bağlayıcıları: həm, həm də, həm də ki, nəinki, o cümlədən, hətta, habelə, həmçinin, da...da (də...də), da, də.
6. Aydınlaşdırma bağlayıcıları: yəni, yəni ki, məsələn.

**Tabelilik bağlayıcıları:**
1. Səbəb bağlayıcıları: çünki, ona görə ki, ona görə də, ondan ötrü ki, onun üçün ki, buna görə də. 
2. Şərt bağlayıcıları: əgər, hərgah, indi ki, madam ki, bir halda ki.
3. Güzəşt bağlayıcıları: hərçənd, hərçənd ki.
4. Aydınlaşdırma bağlayıcıları: ki, belə ki.

**Comment by mastizada** [comment]
Added in version 0.2
